Created basic package structure for rest api backend
moevm/nosql2h21-cats-memecached pull request #2
Opened 2021-09-14 07:07 UTC by snchz29

2021-09-14 07:36 UTC, nechepurenkoN requested changes
Change description in `pom.xml`

2021-09-14 07:36 UTC, nechepurenkoN commented on pom.xml
> +	<description>Demo project for Spring Boot</description>
Is it the relevant description of our project?

2021-09-15 10:01 UTC, Pavel-by approved these changes

2021-09-15 11:21 UTC, Pavel-by requested changes
Нам ведь нужно деление на frontent и backend, решили, насколько я помню, делать их просто в подпапках. Сейчас все файле бека лежат в корне

2021-09-17 13:58 UTC, Pavel-by approved these changes

2021-09-18 10:42 UTC, nechepurenkoN approved these changes

2021-09-21 08:09 UTC, merged